import React from "react";
import {
  AbsoluteFill,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import type { PaperMeta } from "../types";
import type { Theme } from "../theme";

interface Props {
  papers: PaperMeta[];
  digestTitle: string;
  channelName: string;
  theme: Theme;
  fontFamily: string;
}

/** Closing card: thanks + attribution + arXiv link (single) + channel name. */
export const Outro: React.FC<Props> = ({ papers, digestTitle, channelName, theme, fontFamily }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const enter = spring({ frame, fps, config: { damping: 200 }, durationInFrames: 22 });
  const single = papers.length === 1 ? papers[0] : null;
  const subtitle = single
    ? single.title
    : `${digestTitle}  ·  ${papers.length} papers`;

  return (
    <AbsoluteFill
      style={{ alignItems: "center", justifyContent: "center", padding: "0 12%" }}
    >
      <div
        style={{
          opacity: enter,
          transform: `translateY(${interpolate(enter, [0, 1], [20, 0])}px)`,
          textAlign: "center",
        }}
      >
        <div
          style={{
            fontFamily,
            fontWeight: 700,
            fontSize: 56,
            color: theme.textPrimary,
            letterSpacing: -0.3,
          }}
        >
          Thanks for watching
        </div>
        <div
          style={{
            fontFamily,
            fontWeight: 500,
            fontSize: 28,
            color: theme.textMuted,
            marginTop: 28,
            maxWidth: 1200,
            textWrap: "balance",
          }}
        >
          {subtitle}
        </div>
        {single && single.arxivId ? (
          <div
            style={{
              fontFamily,
              fontWeight: 600,
              fontSize: 26,
              color: theme.accent,
              marginTop: 22,
              letterSpacing: 1,
            }}
          >
            arxiv.org/abs/{single.arxivId}
          </div>
        ) : null}
        <div
          style={{
            fontFamily,
            fontSize: 20,
            color: theme.textFaint,
            marginTop: 40,
            letterSpacing: 1.4,
          }}
        >
          Figures © original authors · Generated by {channelName}
        </div>
      </div>
    </AbsoluteFill>
  );
};
